import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Input from '../components/Input'
import Card from '../components/Card'
import { useState, useContext } from 'react'
import { TodoContext } from '../context/AppContext'
import CardContainer from '../components/CardContainer'
import { ITodo, TodoContextInterface } from '../utils/interfaces'

const Home: NextPage = () => {

  const {
    todos,
    saveTodo,
    removeTodo
} : TodoContextInterface = useContext<TodoContextInterface>(TodoContext)

  return (
    <div className="h-screen w-screen bg-gray-400">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col justify-center items-center w-screen">
        <Input saveTodo={saveTodo} todos={todos}/>
        <CardContainer todos={todos}/>
      </main>

    </div>
  )
}

export default Home
