import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Input from '../components/Input'
import Card from '../components/Card'

const Home: NextPage = () => {
  return (
    <div className="h-screen w-screen bg-gray-400">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col justify-center items-center w-screen">
        <Input />
        <Card />
      </main>

    </div>
  )
}

export default Home
